const CLASH_ROYALE_CARDS = [
  { name: 'Esqueletos', elixir: 1, rarity: 'Comum', type: 'Tropa', arena: 2, evolution: true },
  { name: 'Espírito Elétrico', elixir: 1, rarity: 'Comum', type: 'Tropa', arena: 5, evolution: false },
  { name: 'Espírito de Fogo', elixir: 1, rarity: 'Comum', type: 'Tropa', arena: 5, evolution: false },
  { name: 'Espírito de Gelo', elixir: 1, rarity: 'Comum', type: 'Tropa', arena: 8, evolution: true },
  { name: 'Goblins', elixir: 2, rarity: 'Comum', type: 'Tropa', arena: 1, evolution: false },
  { name: 'Goblins Lanceiros', elixir: 2, rarity: 'Comum', type: 'Tropa', arena: 1, evolution: false },
  { name: 'Bombardeiro', elixir: 2, rarity: 'Comum', type: 'Tropa', arena: 2, evolution: true },
  { name: 'Berserker', elixir: 2, rarity: 'Comum', type: 'Tropa', arena: 9, evolution: true },
  { name: 'Arqueiras', elixir: 3, rarity: 'Comum', type: 'Tropa', arena: 0, evolution: true },
  { name: 'Cavaleiro', elixir: 3, rarity: 'Comum', type: 'Tropa', arena: 0, evolution: true },
  { name: 'Gangue de Goblins', elixir: 3, rarity: 'Comum', type: 'Tropa', arena: 9, evolution: false },
  { name: 'Pirotécnica', elixir: 3, rarity: 'Comum', type: 'Tropa', arena: 12, evolution: true },
  { name: 'Entrega Real', elixir: 3, rarity: 'Comum', type: 'Feitiço', arena: 14, evolution: false },
  { name: 'Bárbaros', elixir: 5, rarity: 'Comum', type: 'Tropa', arena: 3, evolution: true },
  { name: 'Patifes', elixir: 5, rarity: 'Comum', type: 'Tropa', arena: 13, evolution: false },
  { name: 'Gigante Real', elixir: 6, rarity: 'Comum', type: 'Tropa', arena: 7, evolution: true },
  { name: 'Bárbaros de Elite', elixir: 6, rarity: 'Comum', type: 'Tropa', arena: 10, evolution: false },
  { name: 'Recrutas Reais', elixir: 7, rarity: 'Comum', type: 'Tropa', arena: 7, evolution: true },
  { name: 'Espírito de Cura', elixir: 1, rarity: 'Rara', type: 'Tropa', arena: 13, evolution: false },
  { name: 'Golem de Gelo', elixir: 2, rarity: 'Rara', type: 'Tropa', arena: 8, evolution: false },
  { name: 'Arbusto Suspeito', elixir: 2, rarity: 'Rara', type: 'Tropa', arena: 13, evolution: false },
  { name: 'Goblin com dardo', elixir: 3, rarity: 'Rara', type: 'Tropa', arena: 9, evolution: true },
  { name: 'Golem de Elixir', elixir: 3, rarity: 'Rara', type: 'Tropa', arena: 14, evolution: false },
  { name: 'Mini P.E.K.K.A', elixir: 4, rarity: 'Rara', type: 'Tropa', arena: 0, evolution: false },
  { name: 'Mosqueteira', elixir: 4, rarity: 'Rara', type: 'Tropa', arena: 0, evolution: true },
  { name: 'Jaula de goblim', elixir: 4, rarity: 'Rara', type: 'Construção', arena: 1, evolution: true },
  { name: 'Valquíria', elixir: 4, rarity: 'Rara', type: 'Tropa', arena: 2, evolution: true },
  { name: 'Aríete de Batalha', elixir: 4, rarity: 'Rara', type: 'Tropa', arena: 3, evolution: true },
  { name: 'Corredor', elixir: 4, rarity: 'Rara', type: 'Tropa', arena: 6, evolution: false },
  { name: 'Curadora Guerreira', elixir: 4, rarity: 'Rara', type: 'Tropa', arena: 8, evolution: false },
  { name: 'Fornalha', elixir: 4, rarity: 'Rara', type: 'Construção', arena: 10, evolution: true },
  { name: 'Eletrocutadores', elixir: 4, rarity: 'Rara', type: 'Tropa', arena: 10, evolution: false },
  { name: 'Goblin Demolidor', elixir: 4, rarity: 'Rara', type: 'Tropa', arena: 12, evolution: false },
  { name: 'Gigante', elixir: 5, rarity: 'Rara', type: 'Tropa', arena: 0, evolution: false },
  { name: 'Mago', elixir: 5, rarity: 'Rara', type: 'Tropa', arena: 5, evolution: true },
  { name: 'Porcos Reais', elixir: 5, rarity: 'Rara', type: 'Tropa', arena: 7, evolution: true },
  { name: 'Três Mosqueteiras', elixir: 9, rarity: 'Rara', type: 'Tropa', arena: 7, evolution: false },
  { name: 'Barril de Bárbaros', elixir: 2, rarity: 'Épica', type: 'Feitiço', arena: 9, evolution: false },
  { name: 'Destruidores de Muros', elixir: 2, rarity: 'Épica', type: 'Tropa', arena: 12, evolution: true },
  { name: 'Barril de Goblins', elixir: 3, rarity: 'Épica', type: 'Feitiço', arena: 4, evolution: true },
  { name: 'Guardas', elixir: 3, rarity: 'Épica', type: 'Tropa', arena: 4, evolution: false },
  { name: 'Exército de Esqueletos', elixir: 3, rarity: 'Épica', type: 'Tropa', arena: 4, evolution: true },
  { name: 'Príncipe das Trevas', elixir: 4, rarity: 'Épica', type: 'Tropa', arena: 7, evolution: false },
  { name: 'Gigante das Runas', elixir: 4, rarity: 'Épica', type: 'Tropa', arena: 9, evolution: false },
  { name: 'Caçador', elixir: 4, rarity: 'Épica', type: 'Tropa', arena: 10, evolution: true },
  { name: 'Bruxa', elixir: 5, rarity: 'Épica', type: 'Tropa', arena: 4, evolution: true },
  { name: 'Príncipe', elixir: 5, rarity: 'Épica', type: 'Tropa', arena: 7, evolution: false },
  { name: 'Lançador', elixir: 5, rarity: 'Épica', type: 'Tropa', arena: 13, evolution: false },
  { name: 'Executor', elixir: 5, rarity: 'Épica', type: 'Tropa', arena: 14, evolution: true },
  { name: 'Carrinho de Canhão', elixir: 5, rarity: 'Épica', type: 'Tropa', arena: 15, evolution: false },
  { name: 'Gigante Esqueleto', elixir: 6, rarity: 'Épica', type: 'Tropa', arena: 8, evolution: false },
  { name: 'Goblin Gigante', elixir: 6, rarity: 'Épica', type: 'Tropa', arena: 9, evolution: true },
  { name: 'P.E.K.K.A', elixir: 7, rarity: 'Épica', type: 'Tropa', arena: 4, evolution: true },
  { name: 'Gigante Elétrico', elixir: 7, rarity: 'Épica', type: 'Tropa', arena: 13, evolution: false },
  { name: 'Golem', elixir: 8, rarity: 'Épica', type: 'Tropa', arena: 10, evolution: false },
  { name: 'Mineiro', elixir: 3, rarity: 'Lendária', type: 'Tropa', arena: 11, evolution: false },
  { name: 'Princesa', elixir: 3, rarity: 'Lendária', type: 'Tropa', arena: 11, evolution: false },
  { name: 'Mago de Gelo', elixir: 3, rarity: 'Lendária', type: 'Tropa', arena: 12, evolution: false },
  { name: 'Fantasma Real', elixir: 3, rarity: 'Lendária', type: 'Tropa', arena: 12, evolution: true },
  { name: 'Bandida', elixir: 3, rarity: 'Lendária', type: 'Tropa', arena: 13, evolution: false },
  { name: 'Pescador', elixir: 3, rarity: 'Lendária', type: 'Tropa', arena: 15, evolution: false },
  { name: 'Mago Elétrico', elixir: 4, rarity: 'Lendária', type: 'Tropa', arena: 11, evolution: false },
  { name: 'Arqueiro Mágico', elixir: 4, rarity: 'Lendária', type: 'Tropa', arena: 13, evolution: false },
  { name: 'Lenhador', elixir: 4, rarity: 'Lendária', type: 'Tropa', arena: 14, evolution: true },
  { name: 'Bruxa Sombria', elixir: 4, rarity: 'Lendária', type: 'Tropa', arena: 14, evolution: false },
  { name: 'Bruxa Mãe', elixir: 4, rarity: 'Lendária', type: 'Tropa', arena: 15, evolution: false },
  { name: 'Domadora de Cordeiro', elixir: 5, rarity: 'Lendária', type: 'Tropa', arena: 11, evolution: false },
  { name: 'Máquina de Goblin', elixir: 5, rarity: 'Lendária', type: 'Tropa', arena: 15, evolution: false },
  { name: 'Sparky', elixir: 6, rarity: 'Lendária', type: 'Tropa', arena: 11, evolution: false },
  { name: 'Imperatriz Espiritual', elixir: 6, rarity: 'Lendária', type: 'Tropa', arena: 15, evolution: false },
  { name: 'Mega Cavaleiro', elixir: 7, rarity: 'Lendária', type: 'Tropa', arena: 11, evolution: true },
  { name: 'Pequeno Príncipe', elixir: 3, rarity: 'Campeão', type: 'Tropa', arena: 18, evolution: false },
  { name: 'Cavaleiro Dourado', elixir: 4, rarity: 'Campeão', type: 'Tropa', arena: 16, evolution: false },
  { name: 'Rei Esqueleto', elixir: 4, rarity: 'Campeão', type: 'Tropa', arena: 16, evolution: false },
  { name: 'Mineiro Bombado', elixir: 4, rarity: 'Campeão', type: 'Tropa', arena: 17, evolution: false },
  { name: 'Rainha Arqueira', elixir: 5, rarity: 'Campeão', type: 'Tropa', arena: 17, evolution: false },
  { name: 'Goblinstein', elixir: 5, rarity: 'Campeão', type: 'Tropa', arena: 18, evolution: false },
  { name: 'Monge', elixir: 5, rarity: 'Campeão', type: 'Tropa', arena: 18, evolution: false },
  { name: 'Bandida Líder', elixir: 6, rarity: 'Campeão', type: 'Tropa', arena: 17, evolution: false },
  { name: 'Morcegos', elixir: 2, rarity: 'Comum', type: 'Tropa', arena: 6, evolution: true },
  { name: 'Servos', elixir: 3, rarity: 'Comum', type: 'Tropa', arena: 0, evolution: false },
  { name: 'Barril de Esqueletos', elixir: 3, rarity: 'Comum', type: 'Tropa', arena: 9, evolution: true },
  { name: 'Dragões Esqueletos', elixir: 4, rarity: 'Comum', type: 'Tropa', arena: 5, evolution: false },
  { name: 'Horda de Servos', elixir: 5, rarity: 'Comum', type: 'Tropa', arena: 10, evolution: false },
  { name: 'Megasservo', elixir: 3, rarity: 'Rara', type: 'Tropa', arena: 3, evolution: false },
  { name: 'Máquina Voadora', elixir: 4, rarity: 'Rara', type: 'Tropa', arena: 6, evolution: false },
  { name: 'Bebê Dragão', elixir: 4, rarity: 'Épica', type: 'Tropa', arena: 4, evolution: true },
  { name: 'Balão', elixir: 5, rarity: 'Épica', type: 'Tropa', arena: 7, evolution: false },
  { name: 'Dragão Elétrico', elixir: 5, rarity: 'Épica', type: 'Tropa', arena: 12, evolution: true },
  { name: 'Dragão Infernal', elixir: 4, rarity: 'Lendária', type: 'Tropa', arena: 11, evolution: true },
  { name: 'Fênix', elixir: 4, rarity: 'Lendária', type: 'Tropa', arena: 12, evolution: false },
  { name: 'Lava Hound', elixir: 7, rarity: 'Lendária', type: 'Tropa', arena: 13, evolution: false },
  { name: 'Zap', elixir: 2, rarity: 'Comum', type: 'Feitiço', arena: 6, evolution: true },
  { name: 'Bola de Neve', elixir: 2, rarity: 'Comum', type: 'Feitiço', arena: 8, evolution: true },
  { name: 'Flechas', elixir: 3, rarity: 'Comum', type: 'Feitiço', arena: 0, evolution: false },
  { name: 'Terremoto', elixir: 3, rarity: 'Rara', type: 'Feitiço', arena: 12, evolution: false },
  { name: 'Bola de Fogo', elixir: 4, rarity: 'Rara', type: 'Feitiço', arena: 0, evolution: false },
  { name: 'Foguete', elixir: 6, rarity: 'Rara', type: 'Feitiço', arena: 6, evolution: false },
  { name: 'Espelho', elixir: 1, rarity: 'Épica', type: 'Feitiço', arena: 15, evolution: false },
  { name: 'Maldição Goblin', elixir: 2, rarity: 'Épica', type: 'Feitiço', arena: 14, evolution: false },
  { name: 'Fúria', elixir: 2, rarity: 'Épica', type: 'Feitiço', arena: 14, evolution: false },
  { name: 'Vinhas', elixir: 3, rarity: 'Épica', type: 'Feitiço', arena: 8, evolution: false },
  { name: 'Clone', elixir: 3, rarity: 'Épica', type: 'Feitiço', arena: 15, evolution: false },
  { name: 'Tornado', elixir: 3, rarity: 'Épica', type: 'Feitiço', arena: 15, evolution: false },
  { name: 'Gelo', elixir: 4, rarity: 'Épica', type: 'Feitiço', arena: 8, evolution: false },
  { name: 'Veneno', elixir: 4, rarity: 'Épica', type: 'Feitiço', arena: 9, evolution: false },
  { name: 'Void', elixir: 3, rarity: 'Épica', type: 'Feitiço', arena: 15, evolution: false },
  { name: 'Relâmpago', elixir: 6, rarity: 'Épica', type: 'Feitiço', arena: 8, evolution: false },
  { name: 'O Tronco', elixir: 2, rarity: 'Lendária', type: 'Feitiço', arena: 11, evolution: false },
  { name: 'Cemitério', elixir: 5, rarity: 'Lendária', type: 'Feitiço', arena: 12, evolution: false },
  { name: 'Canhão', elixir: 3, rarity: 'Comum', type: 'Construção', arena: 3, evolution: true },
  { name: 'Morteiro', elixir: 4, rarity: 'Comum', type: 'Construção', arena: 6, evolution: true },
  { name: 'Tesla', elixir: 4, rarity: 'Comum', type: 'Construção', arena: 10, evolution: true },
  { name: 'Lápide', elixir: 3, rarity: 'Rara', type: 'Construção', arena: 2, evolution: false },
  { name: 'Torre de Bombas', elixir: 4, rarity: 'Rara', type: 'Construção', arena: 5, evolution: false },
  { name: 'Torre Inferno', elixir: 5, rarity: 'Rara', type: 'Construção', arena: 5, evolution: false },
  { name: 'Cabana de Goblins', elixir: 4, rarity: 'Rara', type: 'Construção', arena: 1, evolution: false },
  { name: 'Cabana de Bárbaros', elixir: 6, rarity: 'Rara', type: 'Construção', arena: 9, evolution: false },
  { name: 'Coletor de Elixir', elixir: 6, rarity: 'Rara', type: 'Construção', arena: 15, evolution: false },
  { name: 'Goblin com Broca', elixir: 4, rarity: 'Épica', type: 'Construção', arena: 14, evolution: true },
  { name: 'X-Besta', elixir: 6, rarity: 'Épica', type: 'Construção', arena: 10, evolution: false },
]
module.exports = CLASH_ROYALE_CARDS;